export enum MENU_ITEM_TYPES {
  MAIN = "main",
  ABOUT = "about",
  SCHEDULE = "schedule",
  BOOK = "book",
  USERS = "users",
  ALL_THERAPY_REQUESTS = "allTherapyRequests",
  ALL_THERAPY_REQUESTS_NEW = "allTherapyRequestsNew",
  ALL_THERAPY_REQUESTS_ACCEPTED = "allTherapyRequestsAccepted",
  CLIENTS = "clients",
  CLIENTS_LIST = "clientsList",
  CLIENTS_ADD = "clientsAdd",
  THERAPY_REQUESTS = "therapyRequests",
  THERAPY_REQUESTS_NEW = "therapyRequestsNew",
  THERAPY_REQUESTS_ACCEPTED = "therapyRequestsAccepted",
  SEND_THERAPY_REQUEST = "sendTherapyRequest",
  STATISTIC = "statistic",
  //PERIODS
  WEEK = "week",
  FORTNIGHT = "fortnight",
  MONTH = "month",
}
